///|
#external
type FMTaskRef

///|
#external
type FMSystemLanguageModelRef

///|
#external
type FMLanguageModelSessionRef

///|
#external
type FMLanguageModelSessionResponseStreamRef

///|
#external
type FMGenerationSchemaRef

///|
#external
type FMGeneratedContentRef

///|
#external
type FMGenerationSchemaPropertyRef

///|
#external
type FMBridgedToolRef

///|
#external
type FMComposedPromptRef
